### ISSUE TITLE
No available node version satisfies 'node9'

### ISSUE THREAD

**Issue by Armaldio** [atabel/carlo-nativefier#1]
I got an error when trying to run `carlo-nativefier`:

![image](https://user-images.githubusercontent.com/3089715/49874210-ea02e400-fdeb-11e8-8ed0-bed0c7d72c9c.png)

**Comment by atabel** [comment]
I'm sorry but [pkg](https://github.com/zeit/pkg) does not support node9. These are the supported node versions:
https://github.com/zeit/pkg-fetch/blob/master/patches/patches.json

**Comment by Armaldio** [comment]
Thanks
